version: "3.8"
services:
    account-gql:
        build:
            context: .
            dockerfile: development.dockerfile
        container_name: account-gql
        ports:
            - 8000:8000
        environment: 
            - "APPENV=development"
        volumes:
            - ./:/go/src/github.com/kecci/go-gql-microservice    
        depends_on: 
            - postgres
    postgres:
        image: postgres:12.0-alpine
        environment: 
            POSTGRES_DB: machtwatch-campaign
            POSTGRES_PASSWORD: machtwatch123
            POSTGRES_USER: machtwatch_user
            PGDATA: /var/lib/postgresql/data/machtwatch-campaign
        container_name: postgres-kecci
        volumes: 
            - .docker/postgres-data:/var/lib/postgresql/data/machtwatch-campaign
            - .docker/database_scripts:/docker-entrypoint-initdb.d
            - .docker/seeding/seeds:/seeds
        ports:
            - "5432:5432"
    # redis:
    #     container_name: redis-machtwatch-campaign
    #     image: redis:latest
    #     ports:
    #         - "6379:6379"